In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
%matplotlib inline

In [2]:
df = pd.read_csv("homeprices_banglore.csv")
df.sample(5)
df['price'].shape

(20,)

In [3]:
from sklearn import preprocessing

sx = preprocessing.MinMaxScaler()
sy = preprocessing.MinMaxScaler()

scaled_X = sx.fit_transform(df.drop('price', axis='columns'))
scaled_X


array([[0.08827586, 0.25      ],
       [0.62068966, 0.75      ],
       [0.22068966, 0.5       ],
       [0.24862069, 0.5       ],
       [0.13793103, 0.25      ],
       [0.12758621, 0.25      ],
       [0.6662069 , 0.75      ],
       [0.86206897, 0.75      ],
       [0.17586207, 0.5       ],
       [1.        , 1.        ],
       [0.34482759, 0.5       ],
       [0.68448276, 0.75      ],
       [0.06896552, 0.25      ],
       [0.10344828, 0.25      ],
       [0.5       , 0.5       ],
       [0.12931034, 0.25      ],
       [0.13103448, 0.5       ],
       [0.25517241, 0.5       ],
       [0.67931034, 0.5       ],
       [0.        , 0.        ]])

In [4]:
scaled_y = sy.fit_transform(df['price'].values.reshape(df.shape[0],1))
scaled_y

array([[0.05237037],
       [0.65185185],
       [0.22222222],
       [0.31851852],
       [0.14074074],
       [0.04444444],
       [0.76296296],
       [0.91111111],
       [0.13333333],
       [1.        ],
       [0.37037037],
       [0.8       ],
       [0.04444444],
       [0.05925926],
       [0.51111111],
       [0.07407407],
       [0.11851852],
       [0.20740741],
       [0.51851852],
       [0.        ]])

In [5]:
scaled_y.reshape(scaled_y.shape[0], )
scaled_y

array([[0.05237037],
       [0.65185185],
       [0.22222222],
       [0.31851852],
       [0.14074074],
       [0.04444444],
       [0.76296296],
       [0.91111111],
       [0.13333333],
       [1.        ],
       [0.37037037],
       [0.8       ],
       [0.04444444],
       [0.05925926],
       [0.51111111],
       [0.07407407],
       [0.11851852],
       [0.20740741],
       [0.51851852],
       [0.        ]])

In [6]:
np.dot(np.ones(shape=(scaled_X.shape[1])), scaled_X.T)

array([0.33827586, 1.37068966, 0.72068966, 0.74862069, 0.38793103,
       0.37758621, 1.4162069 , 1.61206897, 0.67586207, 2.        ,
       0.84482759, 1.43448276, 0.31896552, 0.35344828, 1.        ,
       0.37931034, 0.63103448, 0.75517241, 1.17931034, 0.        ])

In [7]:
def batch_gradient_descent(X, y_true, epochs, learning_rate = 0.01):
    
    number_of_features = X.shape[1]
    w = np.ones(shape = (number_of_features))
    bias = 0
    total_samples = X.shape[0]
    cost_list = []
    epoch_list = []

    for i in range(epochs):
        y_predicted = np.dot(w, X.T) + bias

        w_grad = (2/total_samples)*np.dot(X.T, y_predicted-y_true)
        b_grad=  (2/total_samples)*np.sum(y_predicted-y_true)

        w = w - learning_rate*w_grad
        bias = bias - learning_rate*b_grad 

        cost = np.mean(np.square(y_true-y_predicted))

        if(i%10 == 0):
            cost_list.append(cost)
            epoch_list.append(i)

    return w, bias, cost, cost_list, epoch_list

w, bias, cost, cost_list, epoch_list = batch_gradient_descent(scaled_X, scaled_y.reshape(scaled_y.shape[0],), 500)
w, bias, cost


(array([0.70712464, 0.67456527]), -0.23034857438407427, 0.0068641890429808105)

In [94]:
def predict(X):
    #total_samples = X.shape[0]
    if(X.ndim == 1):
        X_scaled = sx.transform(X.values.reshape(1, -1))
    else:
        X_scaled = sx.transform(X.values.reshape(-1, X.shape[1]))
    
    y = np.dot(w, X_scaled.T) + bias
    y_predicted = sy.inverse_transform(y.reshape(-1, 1))
    return y_predicted
    #print(y)

X = df.drop('price', axis='columns')
y = df['price']

yp = predict(X.loc[0:25])
#y.iloc[:3, ]
#predict(pd.DataFrame({'x':[2600], 'y':[4]}))
#scaled_X[0:3]
#scaled_y.reshape(-1, 1)
#print(y[0:25])
[print(yp[i], y.iloc[i]) for i in range(11)]


[32.09649526] 39.07
[128.45484403] 120.0
[67.50353558] 62.0
[70.16988315] 75.0
[36.83666872] 51.0
[35.84913258] 38.0
[132.80000304] 135.0
[151.49735394] 155.0
[63.22421231] 50.0
[187.43108021] 167.0
[79.35396925] 82.0


c:\Users\Acer\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\base.py:439: UserWarning: X does not have valid feature names, but MinMaxScaler was fitted with feature names
  warnings.warn(


[None, None, None, None, None, None, None, None, None, None, None]